
# DataSource Config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.14.106.232:1521:helowin
    username: cyz
    password: caoyhuo
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 9000
